#
#
#

CFLAGS = $(GLOBALFLAGS) -O2 -g -I/usr/include/mysql -I../../include -flto

LL = ../../lib

LOCALSRCS = stalist.c palert.c trh2_enrich.c
LOCALOBJS = $(LOCALSRCS:%.c=%.o)

no_sql: palert.o trh2_enrich.o
	@mv *.o $(LL)

all: $(LOCALOBJS)
	@mv *.o $(LL)

#
.c.o:
	@echo Compiling $<...
	@$(CC) $(CFLAGS) -c $<

# Clean-up rules
clean:
	@echo Cleaning build objects...
	@rm -f a.out core *.o *.obj *% *~

clean_lib:
	@echo Removing libraries...
	@rm -f $(LL)/*.o

PHONY:
